version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - overlay
    volumes:
      - db-data:/var/lib/postgresql
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - overlay
  api:
    container_name: api
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile.dev
    networks:
      - overlay
    volumes:
      - ./:/workspace
    ports:
      - "5000:5000"
    command: /bin/sh -c "while sleep 1000; do :; done"
  app:
    container_name: app
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
      WDS_SOCKET_PORT: 0
    networks:
      - overlay
    volumes:
      - nodemodules:/workspace/app/node_modules
      - ./:/workspace
    ports:
      - "0.0.0.0:3000:3000"
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - api
networks:
  overlay:
volumes:
  db-data:
  nodemodules:

